BEGIN TRANSACTION;
DROP TABLE IF EXISTS "credentials";
CREATE TABLE IF NOT EXISTS "credentials" (
	"id" 	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"addr"	TEXT NOT NULL,
	"login"	TEXT NOT NULL,
	"password"	TEXT NOT NULL,
	"port"	INTEGER,
	"type"	INTEGER
);
DROP TABLE IF EXISTS "users";
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL,
	"role"	INTEGER DEFAULT 0
);

DROP TABLE IF EXISTS "users_creds";
CREATE TABLE IF NOT EXISTS "users_creds" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "user_id" INTEGER,
    "cred_id" INTEGER,
    FOREIGN KEY("user_id") REFERENCES "users"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY("cred_id") REFERENCES "credentials"("id") ON UPDATE CASCADE ON DELETE CASCADE
);
COMMIT;
